### ISSUE TITLE
create nav & sample section

### ISSUE THREAD

**Issue by dprincecoder** [zuri-training/Team_14_CMS#13]
you are to create a navbar from the Figma design, also including the sample text section

**Comment by dprincecoder** [comment]
this issue is fixed

**Comment by holayide** [comment]
It is well done but not responsive

**Comment by dprincecoder** [comment]
Yes! Responsive design is yet to be added

**Comment by holayide** [comment]
All good then

**Comment by dprincecoder** [comment]
cool, this issue is now solved and will be closed
