### ISSUE TITLE
all template page

### ISSUE THREAD

**Issue by dprincecoder** [zuri-training/Team_14_CMS#21]
You are to create the all template page.
The design is in Figma under HI-FI(desktop)

**Comment by DumisaniLesley** [comment]
After looking at the margins of the design, a slight change will be added, for example on the line below the navbar, the margin left is 120px and the margin right is 118px, so for constancy I will use a uniform margin on both.

**Comment by DumisaniLesley** [comment]
Finished the template page
![template page](https://user-images.githubusercontent.com/44291482/183774276-6757dfbf-4f3b-4ce9-bf50-0b3d4dfee55d.png)

**Comment by dprincecoder** [comment]
Add a hover effect on the cards, and a little of box-shadows and cursor pointer

**Comment by DumisaniLesley** [comment]
Is the hover effect stated by the designers or i come up with my own custom one?

**Comment by DumisaniLesley** [comment]
Done...waiting review

**Comment by dprincecoder** [comment]
cool nicely done, do the responsiveness

**Comment by Ukinyang** [comment]
GREAT WORK. Using a uniform margin is good..

**Comment by DumisaniLesley** [comment]
> GREAT WORK. Using a uniform margin is good..

thanks

**Comment by DumisaniLesley** [comment]
Done with mobile responsiveness

**Comment by dprincecoder** [comment]
nice
