### ISSUE TITLE
Design template screens

### ISSUE THREAD

**Issue by Ukinyang** [zuri-training/Team_14_CMS#29]
# Create the following template screens
@eberre28 create blog and portfolio
@ololadetife create blog template
@Ajengsolange create portfolio template
@Ukinyang create resturant template
@AbiolaGold create E-commerce template

**Comment by AbiolaGold** [comment]
@AbiolaGold create E-commerce template

**Comment by AbiolaGold** [comment]
Done

**Comment by ololadetife** [comment]
Template page for blog created

**Comment by eberre28** [comment]
Template for blog and portfolio for CMS created.

**Comment by Ukinyang** [comment]
All assigned template screens created.
