### ISSUE TITLE
create a database schema

### ISSUE THREAD

**Issue by dprincecoder** [zuri-training/Team_14_CMS#44]
you are to create a database schema

**Comment by dprincecoder** [comment]
for this solution, I drew a rough sketch initially how our database will be structured, including the data types it will accept
![WhatsApp Image 2022-08-10 at 3 59 34 PM](https://user-images.githubusercontent.com/78590038/183939129-e1a5a6cd-4217-4b62-bd03-fd2dc5185f0a.jpeg)

**Comment by Ddilibe** [comment]
Implemented the digitalized format of the database @dprincecoder provided on paper. Collaborated with @void-4 and added a lot other new features

**Comment by dprincecoder** [comment]
issue resolved
