### ISSUE TITLE
Presentation slides

### ISSUE THREAD

**Issue by Ukinyang** [zuri-training/Team_14_CMS#50]
#Create presentation slides
@Icematics, @Ukinyang @eberre28
 
the presentation to be done by
@Chukwuebuka2  the presentation

**Comment by eberre28** [comment]
Created some presentation slides for the first presentation

**Comment by Icematics** [comment]
Done

**Comment by Ukinyang** [comment]
slides done
https://www.figma.com/file/kokVUh8TvoS7fkXZs7UPkN/CMS-2-(Team_14)?node-id=55%3A32566

**Comment by Ukinyang** [comment]
presentatio done
