### ISSUE TITLE
User Research

### ISSUE THREAD

**Issue by Icematics** [zuri-training/Team_14_CMS#51]
Screener and Interview questions, google screener form
@Ukinyang and @eberre28 

Research Plan
@AbiolaGold @Olokoaishat  and @Viviyaan

**Comment by AbiolaGold** [comment]
Introduction done

**Comment by Viviyaan** [comment]
Created research plan
Google doc link: https://docs.google.com/document/d/1SNWVdNfsCehIF-7ZQfJ4jOqfmdSPShyutRtudbEmccc/edit

**Comment by Ukinyang** [comment]
interview script queston done

https://docs.google.com/document/d/1dpRM1Nf4hIuQUYLsGecKx-QLifRkK0jQQ1KxxtlxBMw/edit?usp=sharing
